# Generated by Django 5.1.7 on 2025-03-23 10:46

import cloudinary.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('product_description', models.TextField(max_length=200)),
                ('product_quantity', models.IntegerField()),
                ('product_price', models.FloatField(validators=[django.core.validators.MaxValueValidator(1000000.0)])),
                ('product_discount', models.DecimalField(decimal_places=2, help_text='leave it blanck for no discount', max_digits=5)),
                ('product_rating', models.PositiveSmallIntegerField(blank=True, help_text='Value must be between 1 and 5', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.companymodel')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyProductsImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_images', to='products.companyproducts')),
            ],
        ),
    ]
