# Generated by Django 5.1.7 on 2025-03-28 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_companyproducts_product_rating_productrating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyproducts',
            name='product_discount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='leave it blanck for no discount', max_digits=5),
        ),
    ]
